---
name: CI
on:
  pull_request:
  push:

jobs:

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        thread: [ 0, 1, 2 ]
    steps:
      - uses: actions/checkout@v4
      - uses: prometheus/promci@v0.1.0
      - uses: ./.github/promci/actions/build
        with:
          parallelism: 3
          thread: ${{ matrix.thread }}

  publish_release:
    name: Publish release arfefacts
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - uses: prometheus/promci@v0.1.0
      - uses: ./.github/promci/actions/publish_release
        with:
          github_token: ${{ secrets.TOKEN }}
